export const QueryKeys = {
    RetrievePosts: 'retrieve-posts',
    RetrieveAccount: 'retrieve-account',
    RetrieveConnections: 'retrieve-connections',
    RetrieveConnectionRequestById: 'retrieve-connection-request',
    RetrieveConnectionRequests: 'retrieve-connection-requests',
    RetrieveConnectionRequestSent: 'retrieve-connection-requests-sent',
    RetrieveConnectionRequestReceived: 'retrieve-connection-requests-received',
    RetrieveJobs: 'retrieve-jobs',
    RetrieveJobById: 'retrieve-job',
    RetrieveJobsByCompanyId: 'retrieve-jobs-by-companyid',
    RetrieveAllApplicants: 'retrieve-applicants',
    RetrieveAllApplicantsByCompanyId: 'retrieve-applicants-by-companyid',
    RetrieveApplicantById: 'retrieve-applicant',
    RetrieveUserInfo: 'retrieve-user-account',
    RetrieveAppliedJobs: 'retrieve-applied-jobs',
    RetrieveSavedJobsByProfessionalId: 'retrieve-saved-jobs-by-id',
    RetrieveSavedApplicantByCompanyId: 'retrieve-saved-applicants-by-id',
    RetrieveSearchTerm: 'retrieve-search',
    RetrieveProfessionalProfileById: 'retrieve-professional-profile',
    RetrieveCompanyProfileById: 'retrieve-company-profile',
    RetrieveSkills: 'retrieve-skills',
};
